version: '2'
services:
  jenkins-server:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ~/docker-repository/ci_env/jenkins:/var/jenkins_home
    labels:
      - "jenkins.environment=ci"
  sonarqubedb:
    image: mysql:5.7.25
    environment:
      - MYSQL_DATABASE=sonar
      - MYSQL_USER=sonar
      - MYSQL_PASSWORD=sonar
      - MYSQL_ROOT_PASSWORD=supersecret
  sonarqube:
    image: sonarqube:7.7-community
    ports:
      - 9000:9000
    volumes:
      - ~/docker-repository/ci_env/sonarqube/data:/opt/sonarqube/data
      - ~/docker-repository/ci_env/sonarqube/extensions:/opt/sonarqube/extensions
    environment:
      - SONARQUBE_JDBC_URL=jdbc:mysql://sonarqubedb:3306/sonar?useUnicode=true&characterEncoding=utf8
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    links:
      - sonarqubedb
  gerrit:
      image: gerritforge/gerrit-ubuntu15.04:2.13.6
      ports:
        - 8083:8080
        - "29418:29418"
